function link3() {
    // alert(colNum);
    // colNum = 9;
    // colNum = 15;
    // colNum = 17;
    // colNum = 24;
    // colNum = 25;
    // colNum = 27;
    // colNum = 43;
    // colNum = 46;
    // colNum = 64;
    // colNum = 86;
    // colNum = 91;

    if (colNum == 9) {
        document.getElementById("col91Id").value = "3.";          // 小数第19位まで表示
        document.getElementById("col92Id").value = "1";
        document.getElementById("col93Id").value = "4";
        document.getElementById("col94Id").value = "1";
        document.getElementById("col95Id").value = "5";
        document.getElementById("col96Id").value = "9";
        document.getElementById("col97Id").value = "2";
        document.getElementById("col98Id").value = "6";
        document.getElementById("col99Id").value = "5";
        document.getElementById("col100Id").value = "3";
        document.getElementById("col101Id").value = "5";
        document.getElementById("col102Id").value = "8";
        document.getElementById("col103Id").value = "9";
        document.getElementById("col104Id").value = "7";
        document.getElementById("col105Id").value = "9";
        document.getElementById("col106Id").value = "3";
        document.getElementById("col107Id").value = "2";
        document.getElementById("col108Id").value = "3";
        document.getElementById("col109Id").value = "8";
        document.getElementById("col110Id").value = "4";

        colNum = colNum +1;

    } else if (colNum == 15) {
        document.getElementById("col85Id").value = "3.";          // 小数第25位まで表示
        document.getElementById("col86Id").value = "1";
        document.getElementById("col87Id").value = "4";
        document.getElementById("col88Id").value = "1";
        document.getElementById("col89Id").value = "5";
        document.getElementById("col90Id").value = "9";
        document.getElementById("col91Id").value = "2";
        document.getElementById("col92Id").value = "6";
        document.getElementById("col93Id").value = "5";
        document.getElementById("col94Id").value = "3";
        document.getElementById("col95Id").value = "5";
        document.getElementById("col96Id").value = "8";
        document.getElementById("col97Id").value = "9";
        document.getElementById("col98Id").value = "7";
        document.getElementById("col99Id").value = "9";
        document.getElementById("col100Id").value = "3";
        document.getElementById("col101Id").value = "2";
        document.getElementById("col102Id").value = "3";
        document.getElementById("col103Id").value = "8";
        document.getElementById("col104Id").value = "4";
        document.getElementById("col105Id").value = "6";
        document.getElementById("col106Id").value = "2";
        document.getElementById("col107Id").value = "6";
        document.getElementById("col108Id").value = "4";
        document.getElementById("col109Id").value = "3";
        document.getElementById("col110Id").value = "3";

        colNum = colNum +1;

    } else if (colNum == 17) {
        document.getElementById("col83Id").value = "3.";
        document.getElementById("col84Id").value = "1";
        document.getElementById("col85Id").value = "4";
        document.getElementById("col86Id").value = "1";
        document.getElementById("col87Id").value = "5";
        document.getElementById("col88Id").value = "9";
        document.getElementById("col89Id").value = "2";
        document.getElementById("col90Id").value = "6";
        document.getElementById("col91Id").value = "5";
        document.getElementById("col92Id").value = "3";
        document.getElementById("col93Id").value = "5";
        document.getElementById("col94Id").value = "8";
        document.getElementById("col95Id").value = "9";
        document.getElementById("col96Id").value = "7";
        document.getElementById("col97Id").value = "9";
        document.getElementById("col98Id").value = "3";
        document.getElementById("col99Id").value = "2";
        document.getElementById("col100Id").value = "3";    // ☜
        document.getElementById("col101Id").value = "8";
        document.getElementById("col102Id").value = "4";
        document.getElementById("col103Id").value = "6";
        document.getElementById("col104Id").value = "2";
        document.getElementById("col105Id").value = "6";
        document.getElementById("col106Id").value = "4";
        document.getElementById("col107Id").value = "3";
        document.getElementById("col108Id").value = "3";
        document.getElementById("col109Id").value = "8";
        document.getElementById("col110Id").value = "3";    // 小数第27位まで表示

        colNum = colNum +1;

    } else if (colNum == 24) {
        document.getElementById("col76Id").value = "3.";
        document.getElementById("col77Id").value = "1";
        document.getElementById("col78Id").value = "4";
        document.getElementById("col79Id").value = "1";
        document.getElementById("col80Id").value = "5";
        document.getElementById("col81Id").value = "9";
        document.getElementById("col82Id").value = "2";
        document.getElementById("col83Id").value = "6";
        document.getElementById("col84Id").value = "5";
        document.getElementById("col85Id").value = "3";
        document.getElementById("col86Id").value = "5";
        document.getElementById("col87Id").value = "8";
        document.getElementById("col88Id").value = "9";
        document.getElementById("col89Id").value = "7";
        document.getElementById("col90Id").value = "9";
        document.getElementById("col91Id").value = "3";
        document.getElementById("col92Id").value = "2";
        document.getElementById("col93Id").value = "3";
        document.getElementById("col94Id").value = "8";
        document.getElementById("col95Id").value = "4";
        document.getElementById("col96Id").value = "6";
        document.getElementById("col97Id").value = "2";
        document.getElementById("col98Id").value = "6";
        document.getElementById("col99Id").value = "4";
        document.getElementById("col100Id").value = "3";    // ☜
        document.getElementById("col101Id").value = "3";
        document.getElementById("col102Id").value = "8";
        document.getElementById("col103Id").value = "3";
        document.getElementById("col104Id").value = "2";
        document.getElementById("col105Id").value = "7";
        document.getElementById("col106Id").value = "9";
        document.getElementById("col107Id").value = "5";
        document.getElementById("col108Id").value = "0";
        document.getElementById("col109Id").value = "2";
        document.getElementById("col110Id").value = "8";    // 小数第34位

        colNum = colNum +1;

    } else if (colNum == 25) {
        document.getElementById("col75Id").value = "3.";
        document.getElementById("col76Id").value = "1";
        document.getElementById("col77Id").value = "4";
        document.getElementById("col78Id").value = "1";
        document.getElementById("col79Id").value = "5";
        document.getElementById("col80Id").value = "9";
        document.getElementById("col81Id").value = "2";
        document.getElementById("col82Id").value = "6";
        document.getElementById("col83Id").value = "5";
        document.getElementById("col84Id").value = "3";
        document.getElementById("col85Id").value = "5";
        document.getElementById("col86Id").value = "8";
        document.getElementById("col87Id").value = "9";
        document.getElementById("col88Id").value = "7";
        document.getElementById("col89Id").value = "9";
        document.getElementById("col90Id").value = "3";
        document.getElementById("col91Id").value = "2";
        document.getElementById("col92Id").value = "3";
        document.getElementById("col93Id").value = "8";
        document.getElementById("col94Id").value = "4";
        document.getElementById("col95Id").value = "6";
        document.getElementById("col96Id").value = "2";
        document.getElementById("col97Id").value = "6";
        document.getElementById("col98Id").value = "4";
        document.getElementById("col99Id").value = "3";
        document.getElementById("col100Id").value = "3";    // ☜
        document.getElementById("col101Id").value = "8";
        document.getElementById("col102Id").value = "3";
        document.getElementById("col103Id").value = "2";
        document.getElementById("col104Id").value = "7";
        document.getElementById("col105Id").value = "9";
        document.getElementById("col106Id").value = "5";
        document.getElementById("col107Id").value = "0";
        document.getElementById("col108Id").value = "2";
        document.getElementById("col109Id").value = "8";
        document.getElementById("col110Id").value = "8";    // 小数第35位

        colNum = colNum +1;

    } else if (colNum == 27) {
        document.getElementById("col73Id").value = "3.";
        document.getElementById("col74Id").value = "1";
        document.getElementById("col75Id").value = "4";
        document.getElementById("col76Id").value = "1";
        document.getElementById("col77Id").value = "5";
        document.getElementById("col78Id").value = "9";
        document.getElementById("col79Id").value = "2";
        document.getElementById("col80Id").value = "6";
        document.getElementById("col81Id").value = "5";
        document.getElementById("col82Id").value = "3";
        document.getElementById("col83Id").value = "5";
        document.getElementById("col84Id").value = "8";
        document.getElementById("col85Id").value = "9";
        document.getElementById("col86Id").value = "7";
        document.getElementById("col87Id").value = "9";
        document.getElementById("col88Id").value = "3";
        document.getElementById("col89Id").value = "2";
        document.getElementById("col90Id").value = "3";
        document.getElementById("col91Id").value = "8";
        document.getElementById("col92Id").value = "4";
        document.getElementById("col93Id").value = "6";
        document.getElementById("col94Id").value = "2";
        document.getElementById("col95Id").value = "6";
        document.getElementById("col96Id").value = "4";
        document.getElementById("col97Id").value = "3";
        document.getElementById("col98Id").value = "3";
        document.getElementById("col99Id").value = "8";
        document.getElementById("col100Id").value = "3";    // ☜
        document.getElementById("col101Id").value = "2";
        document.getElementById("col102Id").value = "7";
        document.getElementById("col103Id").value = "9";
        document.getElementById("col104Id").value = "5";
        document.getElementById("col105Id").value = "0";
        document.getElementById("col106Id").value = "2";
        document.getElementById("col107Id").value = "8";
        document.getElementById("col108Id").value = "8";
        document.getElementById("col109Id").value = "4";
        document.getElementById("col110Id").value = "1";    // 小数第37位

        colNum = colNum + 1;

    } else if (colNum == 43) {
      document.getElementById("col57Id").value = "3.";
      document.getElementById("col58Id").value = "1";
      document.getElementById("col59Id").value = "4";
      document.getElementById("col60Id").value = "1";
      document.getElementById("col61Id").value = "5";
      document.getElementById("col62Id").value = "9";
      document.getElementById("col63Id").value = "2";
      document.getElementById("col64Id").value = "6";
      document.getElementById("col65Id").value = "5";
      document.getElementById("col66Id").value = "3";
      document.getElementById("col67Id").value = "5";
      document.getElementById("col68Id").value = "8";
      document.getElementById("col69Id").value = "9";
      document.getElementById("col70Id").value = "7";
      document.getElementById("col71Id").value = "9";
      document.getElementById("col72Id").value = "3";
      document.getElementById("col73Id").value = "2";
      document.getElementById("col74Id").value = "3";
      document.getElementById("col75Id").value = "8";
      document.getElementById("col76Id").value = "4";
      document.getElementById("col77Id").value = "6";
      document.getElementById("col78Id").value = "2";
      document.getElementById("col79Id").value = "6";
      document.getElementById("col80Id").value = "4";
      document.getElementById("col81Id").value = "3";
      document.getElementById("col82Id").value = "3";
      document.getElementById("col83Id").value = "8";
      document.getElementById("col84Id").value = "3";
      document.getElementById("col85Id").value = "2";
      document.getElementById("col86Id").value = "7";
      document.getElementById("col87Id").value = "9";
      document.getElementById("col88Id").value = "5";
      document.getElementById("col89Id").value = "0";
      document.getElementById("col90Id").value = "2";
      document.getElementById("col91Id").value = "8";
      document.getElementById("col92Id").value = "8";
      document.getElementById("col93Id").value = "4";
      document.getElementById("col94Id").value = "1";
      document.getElementById("col95Id").value = "9";
      document.getElementById("col96Id").value = "7";
      document.getElementById("col97Id").value = "1";
      document.getElementById("col98Id").value = "6";
      document.getElementById("col99Id").value = "9";
      document.getElementById("col100Id").value = "3";
      document.getElementById("col101Id").value = "9";
      document.getElementById("col102Id").value = "9";
      document.getElementById("col103Id").value = "3";
      document.getElementById("col104Id").value = "7";
      document.getElementById("col105Id").value = "5";
      document.getElementById("col106Id").value = "1";
      document.getElementById("col107Id").value = "0";
      document.getElementById("col108Id").value = "5";
      document.getElementById("col109Id").value = "8";
      document.getElementById("col110Id").value = "2";

        colNum = colNum + 1;

    } else if (colNum == 46) {
      document.getElementById("col54Id").value = "3.";
      document.getElementById("col55Id").value = "1";
      document.getElementById("col56Id").value = "4";
      document.getElementById("col57Id").value = "1";
      document.getElementById("col58Id").value = "5";
      document.getElementById("col59Id").value = "9";
      document.getElementById("col60Id").value = "2";
      document.getElementById("col61Id").value = "6";
      document.getElementById("col62Id").value = "5";
      document.getElementById("col63Id").value = "3";
      document.getElementById("col64Id").value = "5";
      document.getElementById("col65Id").value = "8";
      document.getElementById("col66Id").value = "9";
      document.getElementById("col67Id").value = "7";
      document.getElementById("col68Id").value = "9";
      document.getElementById("col69Id").value = "3";
      document.getElementById("col70Id").value = "2";
      document.getElementById("col71Id").value = "3";
      document.getElementById("col72Id").value = "8";
      document.getElementById("col73Id").value = "4";
      document.getElementById("col74Id").value = "6";
      document.getElementById("col75Id").value = "2";
      document.getElementById("col76Id").value = "6";
      document.getElementById("col77Id").value = "4";
      document.getElementById("col78Id").value = "3";
      document.getElementById("col79Id").value = "3";
      document.getElementById("col80Id").value = "8";
      document.getElementById("col81Id").value = "3";
      document.getElementById("col82Id").value = "2";
      document.getElementById("col83Id").value = "7";
      document.getElementById("col84Id").value = "9";
      document.getElementById("col85Id").value = "5";
      document.getElementById("col86Id").value = "0";
      document.getElementById("col87Id").value = "2";
      document.getElementById("col88Id").value = "8";
      document.getElementById("col89Id").value = "8";
      document.getElementById("col90Id").value = "4";
      document.getElementById("col91Id").value = "1";
      document.getElementById("col92Id").value = "9";
      document.getElementById("col93Id").value = "7";
      document.getElementById("col94Id").value = "1";
      document.getElementById("col95Id").value = "6";
      document.getElementById("col96Id").value = "9";
      document.getElementById("col97Id").value = "3";
      document.getElementById("col98Id").value = "9";
      document.getElementById("col99Id").value = "9";
      document.getElementById("col100Id").value = "3";
      document.getElementById("col101Id").value = "7";
      document.getElementById("col102Id").value = "5";
      document.getElementById("col103Id").value = "1";
      document.getElementById("col104Id").value = "0";
      document.getElementById("col105Id").value = "5";
      document.getElementById("col106Id").value = "8";
      document.getElementById("col107Id").value = "2";
      document.getElementById("col108Id").value = "0";
      document.getElementById("col109Id").value = "9";
      document.getElementById("col110Id").value = "7";

        colNum = colNum + 1;

    } else if (colNum == 64) {
      document.getElementById("col36Id").value = "3.";
      document.getElementById("col37Id").value = "1";
      document.getElementById("col38Id").value = "4";
      document.getElementById("col39Id").value = "1";
      document.getElementById("col40Id").value = "5";
      document.getElementById("col41Id").value = "9";
      document.getElementById("col42Id").value = "2";
      document.getElementById("col43Id").value = "6";
      document.getElementById("col44Id").value = "5";
      document.getElementById("col45Id").value = "3";
      document.getElementById("col46Id").value = "5";
      document.getElementById("col47Id").value = "8";
      document.getElementById("col48Id").value = "9";
      document.getElementById("col49Id").value = "7";
      document.getElementById("col50Id").value = "9";
      document.getElementById("col51Id").value = "3";
      document.getElementById("col52Id").value = "2";
      document.getElementById("col53Id").value = "3";
      document.getElementById("col54Id").value = "8";
      document.getElementById("col55Id").value = "4";
      document.getElementById("col56Id").value = "6";
      document.getElementById("col57Id").value = "2";
      document.getElementById("col58Id").value = "6";
      document.getElementById("col59Id").value = "4";
      document.getElementById("col60Id").value = "3";
      document.getElementById("col61Id").value = "3";
      document.getElementById("col62Id").value = "8";
      document.getElementById("col63Id").value = "3";
      document.getElementById("col64Id").value = "2";
      document.getElementById("col65Id").value = "7";
      document.getElementById("col66Id").value = "9";
      document.getElementById("col67Id").value = "5";
      document.getElementById("col68Id").value = "0";
      document.getElementById("col69Id").value = "2";
      document.getElementById("col70Id").value = "8";
      document.getElementById("col71Id").value = "8";
      document.getElementById("col72Id").value = "4";
      document.getElementById("col73Id").value = "1";
      document.getElementById("col74Id").value = "9";
      document.getElementById("col75Id").value = "7";
      document.getElementById("col76Id").value = "1";
      document.getElementById("col77Id").value = "6";
      document.getElementById("col78Id").value = "9";
      document.getElementById("col79Id").value = "3";
      document.getElementById("col80Id").value = "9";
      document.getElementById("col81Id").value = "9";
      document.getElementById("col82Id").value = "3";
      document.getElementById("col83Id").value = "7";
      document.getElementById("col84Id").value = "5";
      document.getElementById("col85Id").value = "1";
      document.getElementById("col86Id").value = "0";
      document.getElementById("col87Id").value = "5";
      document.getElementById("col88Id").value = "8";
      document.getElementById("col89Id").value = "2";
      document.getElementById("col90Id").value = "0";
      document.getElementById("col91Id").value = "9";
      document.getElementById("col92Id").value = "7";
      document.getElementById("col93Id").value = "4";
      document.getElementById("col94Id").value = "9";
      document.getElementById("col95Id").value = "4";
      document.getElementById("col96Id").value = "4";
      document.getElementById("col97Id").value = "5";
      document.getElementById("col98Id").value = "9";
      document.getElementById("col99Id").value = "2";
      document.getElementById("col100Id").value ="3";
      document.getElementById("col101Id").value = "0";
      document.getElementById("col102Id").value = "7";
      document.getElementById("col103Id").value = "8";
      document.getElementById("col104Id").value = "1";
      document.getElementById("col105Id").value = "6";
      document.getElementById("col106Id").value = "4";
      document.getElementById("col107Id").value = "0";
      document.getElementById("col108Id").value = "6";
      document.getElementById("col109Id").value = "2";
      document.getElementById("col110Id").value = "8";

        colNum = colNum + 1;

    } else if (colNum == 86) {
      document.getElementById("col14Id").value = "3.";
      document.getElementById("col15Id").value = "1";
      document.getElementById("col16Id").value = "4";
      document.getElementById("col17Id").value = "1";
      document.getElementById("col18Id").value = "5";
      document.getElementById("col19Id").value = "9";
      document.getElementById("col20Id").value = "2";
      document.getElementById("col21Id").value = "6";
      document.getElementById("col22Id").value = "5";
      document.getElementById("col23Id").value = "3";
      document.getElementById("col24Id").value = "5";
      document.getElementById("col25Id").value = "8";
      document.getElementById("col26Id").value = "9";
      document.getElementById("col27Id").value = "7";
      document.getElementById("col28Id").value = "9";
      document.getElementById("col29Id").value = "3";
      document.getElementById("col30Id").value = "2";
      document.getElementById("col31Id").value = "3";
      document.getElementById("col32Id").value = "8";
      document.getElementById("col33Id").value = "4";
      document.getElementById("col34Id").value = "6";
      document.getElementById("col35Id").value = "2";
      document.getElementById("col36Id").value = "6";
      document.getElementById("col37Id").value = "4";
      document.getElementById("col38Id").value = "3";
      document.getElementById("col39Id").value = "3";
      document.getElementById("col40Id").value = "8";
      document.getElementById("col41Id").value = "3";
      document.getElementById("col42Id").value = "2";
      document.getElementById("col43Id").value = "7";
      document.getElementById("col44Id").value = "9";
      document.getElementById("col45Id").value = "5";
      document.getElementById("col46Id").value = "0";
      document.getElementById("col47Id").value = "2";
      document.getElementById("col48Id").value = "8";
      document.getElementById("col49Id").value = "8";
      document.getElementById("col50Id").value = "4";
      document.getElementById("col51Id").value = "1";
      document.getElementById("col52Id").value = "9";
      document.getElementById("col53Id").value = "7";
      document.getElementById("col54Id").value = "1";
      document.getElementById("col55Id").value = "6";
      document.getElementById("col56Id").value = "9";
      document.getElementById("col57Id").value = "3";
      document.getElementById("col58Id").value = "9";
      document.getElementById("col59Id").value = "9";
      document.getElementById("col60Id").value = "3";
      document.getElementById("col61Id").value = "7";
      document.getElementById("col62Id").value = "5";
      document.getElementById("col63Id").value = "1";
      document.getElementById("col64Id").value = "0";
      document.getElementById("col65Id").value = "5";
      document.getElementById("col66Id").value = "8";
      document.getElementById("col67Id").value = "2";
      document.getElementById("col68Id").value = "0";
      document.getElementById("col69Id").value = "9";
      document.getElementById("col70Id").value = "7";
      document.getElementById("col71Id").value = "4";
      document.getElementById("col72Id").value = "9";
      document.getElementById("col73Id").value = "4";
      document.getElementById("col74Id").value = "4";
      document.getElementById("col75Id").value = "5";
      document.getElementById("col76Id").value = "9";
      document.getElementById("col77Id").value = "2";
      document.getElementById("col78Id").value = "3";
      document.getElementById("col79Id").value = "0";
      document.getElementById("col80Id").value = "7";
      document.getElementById("col81Id").value = "8";
      document.getElementById("col82Id").value = "1";
      document.getElementById("col83Id").value = "6";
      document.getElementById("col84Id").value = "4";
      document.getElementById("col85Id").value = "0";
      document.getElementById("col86Id").value = "6";
      document.getElementById("col87Id").value = "2";
      document.getElementById("col88Id").value = "8";
      document.getElementById("col89Id").value = "6";
      document.getElementById("col90Id").value = "2";
      document.getElementById("col91Id").value = "0";
      document.getElementById("col92Id").value = "8";
      document.getElementById("col93Id").value = "9";
      document.getElementById("col94Id").value = "9";
      document.getElementById("col95Id").value = "8";
      document.getElementById("col96Id").value = "6";
      document.getElementById("col97Id").value = "2";
      document.getElementById("col98Id").value = "8";
      document.getElementById("col99Id").value = "0";
      document.getElementById("col100Id").value = "3";
      document.getElementById("col101Id").value = "4";
      document.getElementById("col102Id").value = "8";
      document.getElementById("col103Id").value = "2";
      document.getElementById("col104Id").value = "5";
      document.getElementById("col105Id").value = "3";
      document.getElementById("col106Id").value = "4";
      document.getElementById("col107Id").value = "2";
      document.getElementById("col108Id").value = "1";
      document.getElementById("col109Id").value = "1";
      document.getElementById("col110Id").value = "7";

        colNum = colNum + 1;

    } else if (colNum == 91) {
      document.getElementById("col09Id").value = "3.";
      document.getElementById("col10Id").value = "1";
      document.getElementById("col11Id").value = "4";
      document.getElementById("col12Id").value = "1";
      document.getElementById("col13Id").value = "5";
      document.getElementById("col14Id").value = "9";
      document.getElementById("col15Id").value = "2";
      document.getElementById("col16Id").value = "6";
      document.getElementById("col17Id").value = "5";
      document.getElementById("col18Id").value = "3";
      document.getElementById("col19Id").value = "5";
      document.getElementById("col20Id").value = "8";
      document.getElementById("col21Id").value = "9";
      document.getElementById("col22Id").value = "7";
      document.getElementById("col23Id").value = "9";
      document.getElementById("col24Id").value = "3";
      document.getElementById("col25Id").value = "2";
      document.getElementById("col26Id").value = "3";
      document.getElementById("col27Id").value = "8";
      document.getElementById("col28Id").value = "4";
      document.getElementById("col29Id").value = "6";
      document.getElementById("col30Id").value = "2";
      document.getElementById("col31Id").value = "6";
      document.getElementById("col32Id").value = "4";
      document.getElementById("col33Id").value = "3";
      document.getElementById("col34Id").value = "3";
      document.getElementById("col35Id").value = "8";
      document.getElementById("col36Id").value = "3";
      document.getElementById("col37Id").value = "2";
      document.getElementById("col38Id").value = "7";
      document.getElementById("col39Id").value = "9";
      document.getElementById("col40Id").value = "5";
      document.getElementById("col41Id").value = "0";
      document.getElementById("col42Id").value = "2";
      document.getElementById("col43Id").value = "8";
      document.getElementById("col44Id").value = "8";
      document.getElementById("col45Id").value = "4";
      document.getElementById("col46Id").value = "1";
      document.getElementById("col47Id").value = "9";
      document.getElementById("col48Id").value = "7";
      document.getElementById("col49Id").value = "1";
      document.getElementById("col50Id").value = "6";
      document.getElementById("col51Id").value = "9";
      document.getElementById("col52Id").value = "3";
      document.getElementById("col53Id").value = "9";
      document.getElementById("col54Id").value = "9";
      document.getElementById("col55Id").value = "3";
      document.getElementById("col56Id").value = "7";
      document.getElementById("col57Id").value = "5";
      document.getElementById("col58Id").value = "1";
      document.getElementById("col59Id").value = "0";
      document.getElementById("col60Id").value = "5";
      document.getElementById("col61Id").value = "8";
      document.getElementById("col62Id").value = "2";
      document.getElementById("col63Id").value = "0";
      document.getElementById("col64Id").value = "9";
      document.getElementById("col65Id").value = "7";
      document.getElementById("col66Id").value = "4";
      document.getElementById("col67Id").value = "9";
      document.getElementById("col68Id").value = "4";
      document.getElementById("col69Id").value = "4";
      document.getElementById("col70Id").value = "5";
      document.getElementById("col71Id").value = "9";
      document.getElementById("col72Id").value = "2";
      document.getElementById("col73Id").value = "3";
      document.getElementById("col74Id").value = "0";
      document.getElementById("col75Id").value = "7";
      document.getElementById("col76Id").value = "8";
      document.getElementById("col77Id").value = "1";
      document.getElementById("col78Id").value = "6";
      document.getElementById("col79Id").value = "4";
      document.getElementById("col80Id").value = "0";
      document.getElementById("col81Id").value = "6";
      document.getElementById("col82Id").value = "2";
      document.getElementById("col83Id").value = "8";
      document.getElementById("col84Id").value = "6";
      document.getElementById("col85Id").value = "2";
      document.getElementById("col86Id").value = "0";
      document.getElementById("col87Id").value = "8";
      document.getElementById("col88Id").value = "9";
      document.getElementById("col89Id").value = "9";
      document.getElementById("col90Id").value = "8";
      document.getElementById("col91Id").value = "6";
      document.getElementById("col92Id").value = "2";
      document.getElementById("col93Id").value = "8";
      document.getElementById("col94Id").value = "0";
      document.getElementById("col95Id").value = "3";
      document.getElementById("col96Id").value = "4";
      document.getElementById("col97Id").value = "8";
      document.getElementById("col98Id").value = "2";
      document.getElementById("col99Id").value = "5";
      document.getElementById("col100Id").value = "3";
      document.getElementById("col101Id").value = "4";
      document.getElementById("col102Id").value = "2";
      document.getElementById("col103Id").value = "1";
      document.getElementById("col104Id").value = "1";
      document.getElementById("col105Id").value = "7";
      document.getElementById("col106Id").value = "0";
      document.getElementById("col107Id").value = "6";
      document.getElementById("col108Id").value = "7";
      document.getElementById("col109Id").value = "";
      document.getElementById("col110Id").value = "";

        colNum = colNum + 1;

    } else {
        clickMissCount = clickMissCount + 1;

        document.getElementById("clickMissId").innerHTML = clickMiss18p();
        function clickMiss18p() {
            cm18 = "クリックミス:" + clickMissCount + "回"
            return cm18;
        }
      }
  
        /* 経過時間の表示 */
        piStop = new Date();  // 経過時間を退避
        piTime = piStop.getTime() - piStart.getTime();     // 通算ミリ秒計算
            piH = Math.floor(piTime/(60*60*1000));         // '時間'取得
            piTime = piTime - (piH*60*60*1000);
            piM = Math.floor(piTime/(60*1000));            // '分'取得
            piTime = piTime - (piM*60*1000);
            piS = Math.floor(piTime/1000);                 // '秒'取得
            piMS = piTime%1000;                            // 'ミリ秒'取得
  
        document.getElementById("elapsedTimeId").innerHTML = elapsedTime18p();
        function elapsedTime18p() {
            et18 = "タイム:" + piM + "分" + piS + "秒" + piMS;
            return et18;
        }
  
        /* スコアの表示 */
        resultedScore = piM * 60 + piS + clickMissCount + piMS / 1000;
  
        document.getElementById("scoreId").innerHTML = resultedScore18p();
        function resultedScore18p() {
          rs18 = "スコア:" + resultedScore;
          return rs18;
        }
  }
